RAMDON_USER_SCHEMA = schema = {
    "gender": "string",
    "email": "string",
    "phone": "string",
    "cell": "string",
    "nat": "string",
    "name_title": "string",
    "name_first": "string",
    "name_last": "string",
    "location_street_number": "Int16",
    "location_street_name": "string",
    "location_city": "string",
    "location_state": "string",
    "location_country": "string",
    "location_postcode": "string",
    "location_coordinates_latitude": "float32",
    "location_coordinates_longitude": "float32",
    "location_timezone_offset": "string",
    "location_timezone_description": "string",
    "login_uuid": "string",
    "login_username": "string",
    "login_password": "string",
    "login_salt": "string",
    "login_md5": "string",
    "login_sha1": "string",
    "login_sha256": "string",
    "dob_date": "datetime64[ns, UTC]",
    "dob_age": "Int16",
    "registered_date": "datetime64[ns, UTC]",
    "registered_age": "Int16",
    "id_name": "string",
    "id_value": "string",
    "picture_large": "string",
    "picture_medium": "string",
    "picture_thumbnail": "string"
}
